### PR TITLE
chore: do not log database password

### PR DESCRIPTION
**Pull request by flxxyz**
## Description

This change can be displayed as hidden text in the log

## Motivation and Context

I don't want sensitive information to be logged, as it could potentially be exposed in the log management of other services (such as docker or k8s).

## Types of changes

- [x] Non-functional change (docs, style, minor refactor)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my code changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by Cameri** [comment]
@flxxyz thanks for contributing! do you mind linting and including unit tests for your changes?

**Comment by Cameri** [comment]
or even better, we could just get rid of the `debug` statements logging the db config

**Comment by flxxyz** [comment]
>

**Comment by flxxyz** [comment]
> or even better, we could just get rid of the `debug` statements logging the db config

yeah, sounds good to me

**Comment by Cameri** [comment]
@flxxyz  please let me know if you'll push a new commit

**Comment by flxxyz** [comment]
> @flxxyz please let me know if you'll push a new commit

submitted!

**Review by Cameri — APPROVED** [review]

**Comment by Cameri** [comment]
@flxxyz changes look good but the linter is complaining. Could you please fix the lint issue and ensure `npm run lint` exists successfully?

**Comment by Cameri** [comment]
@flxxyz bump

**Pull request closed without merging**
